### ISSUE TITLE
Chrome aw-snap

### ISSUE THREAD

**Issue by parkaran** [pqina/vue-filepond#121] opened 2019-12-23 17:51 UTC
### Summary
Hi, i'm getting the Chrome aw-snap page when using file pond in the vuetify v-window component.

i have a file-pond in the step one and when i go from step 1 to 2 and back multiple time chrome gives the aw-snap page.

i'v also created a codesandbox to reproduce the problem:
https://codesandbox.io/s/amazing-smoke-bpbq5

| Environment  | Version
|------------- | -----------
| OS           | Windows 10
| Device       | Desktop
| Browser      | Chrome latest version (64 bit)

**Comment by chasegiunta** [comment] 2019-12-30 15:34
I also am seeing this error. Similar situation: being used in a multistep form, and upon navigating back to the step where filepond is being used, and trying to navigate away from that step, filepond crashes the whole tab, sometimes the whole browser.

**Comment by rikschennink** [comment] 2019-12-30 15:41
Hm, weird. Maybe it's the MutationObserver. I've tried to reproduce it in the code sandbox but it's working correctly so far.

**Comment by chasegiunta** [comment] 2019-12-30 15:42
@rikschennink Just to clarify, vuetify is not required. Essentially the very minimum to create this would be to mount the filepond component, hide it with v-if/v-show, show it again, and then hide it again.

**Comment by chasegiunta** [comment] 2019-12-30 15:47
I can't recreate it either with the codesandbox oddly enough. I'll try to create my own repro.

**Comment by rikschennink** [comment] 2019-12-30 15:48
@chasegiunta that would be very much appreciated. If you can, please copy past the FilePond component directly to the sandbox (instead of the npm module), that makes it easier to edit the code.

**Comment by chasegiunta** [comment] 2019-12-30 17:18
@parkaran wondering if you're still seeing this error on your end, and in your codesandbox you shared.

@rikschennink I'm unable to reproduce this on my own in codesandbox. There is a some things to note though that I noticed debugging on my local project:

I'm using a multistep form. Changing steps on this form uses not only Vue's transitions, but also https://github.com/guanzo/vue-smooth-reflow for transitioning the dynamic height of the form container. Basically, there's a lot of paint logic going on (I noticed @parkaran use-case also was using transitions between steps, etc.)

If I remove the Filepond component, I can't reproduce this Chrome crash. If I remove the vue transitions & smooth-reflow, I can't reproduce this Chrome crash.

Honestly (total theory here), this may just be a perfect cocktail of throwing too much at Chrome's paint engine or something of the like (mounting filepond, mounting fields transitioning all these DOM elements, etc)... I don't know why it's just showing up _now_, maybe something in a recent Chrome update, but it also sounds like while Filepond could take some steps to prevent this crash, it ultimately may not land on Filepond being at fault. Btw, I'm on a completely different machine than @parkaran (Newest 2019 Macbook Pro) - doesn't seem like a lack of resources issue, rather an issue with Chrome not handling something correctly.

If I run Chrome's logging, these are what show up during the crash. 2nd line may just be an error in logging a snapshot, but it would be interesting to see what the errors show as on a Windows machine during the crash.
```
[1228/135719.296379:WARNING:process_memory_mac.cc(93)] mach_vm_read(0x7ffee9c4f000, 0x2000): (os/kern) invalid address (1)
[1228/135719.377129:WARNING:system_snapshot_mac.cc(42)] sysctlbyname kern.nx: No such file or directory (2)
```

For now, I'll be removing transitions between form steps, and hope that works for all other users.

**Comment by parkaran** [comment] 2019-12-30 20:29
A month ago didn't had any issue until chrome update (79.0.3945.79) came.

@chasegiunta i can't reproduce every time the error in the code sandbox, but it happens sometimes if you use 'open in new window' option and try navigating thru step 1 and 2 multiple times.
But in the project i'm working on it happens EVERY time when i have a file-pond in a multi step form, it may be because i have a lot of stuff going on in the different steps and Chrome's paint engine isn't able to handle, but if i remove the file-pond component every thing works fine

**Comment by rikschennink** [comment] 2019-12-31 07:25
@chasegiunta thanks for the effort! 🙏

@parkaran I just retested using open in new window on Chrome 79 on MacOS and on Windows but unfortunately it doesn't trigger the error.

It's a weird bug, the multi-step component simply hides FilePond using `display:none` (it doesn't remove it from the DOM so the MutationObserver is not causing this) and while FilePond has an active draw loop running in the background it checks if it's visible and if it isn't then it just stops updating.

**Comment by webjohan** [comment] 2020-01-20 13:42
I've recreated a "Aw, snap!" moment. Are you using multiple Filepond components? Like uploading two different images to two different Fileponds?

**Comment by webjohan** [comment] 2020-01-20 13:55
We use ngx-filepond. It's a really weird case. 
To recreate:
Use multiple filepond inputs. They should have the same name for this to "work" (which is default if you use multiple "fileponds" and don't set each name different.
You also have to put the "fileponds" inside an element that you will toggle using transitions.

This is the css that causes every thing to go snap:
.filepond--root .filepond--drop-label {
	min-height: 4.75em;
}

Codepen example:
https://codepen.io/webjohan/pen/VwYVrGv
You have to multiclick/doubble click on the test link.
remove:
.filepond--root .filepond--drop-label {
	min-height: 4.75em;
}
and it will not crash

Also try changing to unique names for the inputs to verify that it doesn't crash.
(name="filepond1" name="filepond2" etc)

Note: when you crash the codepen view ... just edit the html and it will get rid of the sad computer.

**Comment by rikschennink** [comment] 2020-01-21 12:25
@webjohan Thanks for creating the test case, a couple clicks and indeed it crashed the browser. Going to dive in to this later this week.

**Comment by webjohan** [comment] 2020-01-21 13:45
This is most likely a Chrome issue rather than Filepond. I've also filed a bug report with the Chrome team.

**Comment by rikschennink** [comment] 2020-01-22 19:05
@webjohan Can you post a link to the issue

**Comment by rikschennink** [comment] 2020-01-22 19:12
I'll close this one and re-open the referenced issue (as it's unrelated to Vue), let's move the discussion there.

**Closed by rikschennink** 2020-01-22 19:12 UTC

**Comment by webjohan** [comment] 2020-01-23 07:46
@rikschennink I filed it in the browser and go no feedback on any issue number.

**Comment by rikschennink** [comment] 2020-01-23 07:47
@webjohan okay, no worries 👍

**Comment by webjohan** [comment] 2020-01-23 11:25
But now I’ve filed a “real” issue. I’ll post the link after lunch.
