### ISSUE TITLE
Initial files setup breaks translate styles

### ISSUE THREAD

**Issue by bionicmaster** [pqina/vue-filepond#52] opened 2018-09-27 11:02 UTC
### Summary
When I try to load initial files (because I already upload it and just want to maintain there as indicators) the list is dropped with the transform outside the container

### How to reproduce
Create a box as container
Insert some files (with mock in my case)
Show what's going on with the list of files

### Expected behaviour

List to be inside the container

### Additional information

| Environment  | Version
|------------- | -----------
| OS           | MacOS
| Device       | Macbook Pro
| Browser      | Chrome 69

**Comment by rikschennink** [comment] 2018-09-27 13:06
I can't reproduce this problem, can you create a publicly accessible test case.

**Comment by rikschennink** [comment] 2018-10-15 06:06
Managed to reproduce the issue. It's probably fixed with the latest `4.0.0` update.

**Closed by rikschennink** 2018-10-15 06:06 UTC
